### ISSUE TITLE
excel download

### ISSUE THREAD

**Issue by ghost** [nicolaslopezj/excel-export#4]
ERROR - Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.
  How can solve this ?

**Comment by nicolaslopezj** [comment]
You could use my roles package and do it like this:

Create a key
https://github.com/nicolaslopezj/orion-exporter/blob/master/exporter_client.js#L33

Get the userId with the key
https://github.com/nicolaslopezj/orion-exporter/blob/master/exporter_server.js#L5

**Comment by nicolaslopezj** [comment]
I will close this issue because its not a problem with this package, but you can still ask questions here.
