### ISSUE TITLE
Excel is not defined 

### ISSUE THREAD

**Issue by jbethuel** [nicolaslopezj/excel-export#5]
thanks for this package! after following the docs I am getting an error which is "Excel is not defined". what could be the problem here?

**Comment by nicolaslopezj** [comment]
Try this:

``` js
import {Excel} from 'meteor/nicolaslopezj:excel-export'
```

**Comment by stefanve** [comment]
Name collision when using netanelgilad:excel 
Installing nicolaslopezj:excel-export makes netanelgilad:excel stop working

var excel = new Excel('xlsx');  gives "Excel is not a function"

**Comment by nicolaslopezj** [comment]
and can you do ```import {Excel} from 'meteor/netanelgilad:excel'``` ?
